### ISSUE TITLE
Not working in discord threads

### ISSUE THREAD

**Issue by itskando** [Vagabottos/rootbot#51]
Could be related to this:

https://support.discord.com/hc/en-us/community/posts/4405219676951-Bots-in-threads

**Comment by seiyria** [comment]
Extremely likely. I don't have the time or resources to fix this, but I'd be happy to review a fix if someone had one.

**Comment by itskando** [comment]
How do you even see which API the app is running on?
I poured through the documentation, but I can't find anything which gives this simple value.

I don't have much coding experience, but if it's as simple as updating the foundational API and that doesn't break anything, I'll try to make a fork and do that and see what happens.

**Comment by seiyria** [comment]
You can look here in the package.json file: https://github.com/Vagabottos/rootbot/blob/master/package.json#L36

Lamentably, we're already on discord.js 12. Also, last time I updated it, it took a few hours because there were a lot of subtle changes that needed to be addressed. In fairness I'm not sure what the actual solution is here, but I think in your thread the root cause is that the bot is not in the thread, and has to be added to the thread. I don't know if there's a way that the bot can always be in a thread.

**Comment by itskando** [comment]
That one I had tried already - texting @vaga in the thread brought them in, but commands still did not function there.

Also, alright - updating has a propensity for breaks.

**Comment by seiyria** [comment]
it works now, with slash commands

**Comment by itskando** [comment]
Yessssss ☺️
